name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version-file: package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry & target
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Commitlint
        run: pnpm exec commitlint --from=${{ github.sha }}

      - name: Check formatting
        # language=bash
        run: |
          cargo fmt --check
          pnpm exec prettier --check .

      - name: Check types
        run: cargo check --workspace

      - name: Lint with Clippy
        run: cargo clippy --workspace -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry & target
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Run tests
        run: cargo test --workspace
